[project]
name = "menace"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "matplotlib>=3.10.7",
  "pandas>=2.3.3",
  "pyarrow>=21.0.0",
  "pyyaml>=6.0.3",
  "scipy>=1.12.0",
  "seaborn>=0.13.2",
]

[dependency-groups]
dev = ["ipykernel>=7.0.0", "markitdown[all]>=0.1.3"]
